import { Data, IProductInput, IUserInput } from "@/types";
import { toSlug } from "./utils";
import bcrypt from "bcryptjs";

const users: IUserInput[] = [
  {
    name: "John",
    email: "admin@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "Admin",
    address: {
      fullName: "John Doe",
      street: "111 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10001",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Jane",
    email: "jane@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Jane Harris",
      street: "222 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1002",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Jack",
    email: "jack@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Jack Ryan",
      street: "333 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1003",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Sarah",
    email: "sarah@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Sarah Smith",
      street: "444 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1005",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Michael",
    email: "michael@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "John Alexander",
      street: "555 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1006",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Emily",
    email: "emily@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Emily Johnson",
      street: "666 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10001",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Alice",
    email: "alice@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Alice Cooper",
      street: "777 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10007",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Tom",
    email: "tom@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Tom Hanks",
      street: "888 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10008",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Linda",
    email: "linda@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Linda Holmes",
      street: "999 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10009",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "George",
    email: "george@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "George Smith",
      street: "101 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10010",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Jessica",
    email: "jessica@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Jessica Brown",
      street: "102 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10011",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Chris",
    email: "chris@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Chris Evans",
      street: "103 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10012",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
  {
    name: "Samantha",
    email: "samantha@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Samantha Wilson",
      street: "104 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10013",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "David",
    email: "david@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "David Lee",
      street: "105 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10014",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Anna",
    email: "anna@example.com",
    password: bcrypt.hashSync("123456", 5),
    role: "User",
    address: {
      fullName: "Anna Smith",
      street: "106 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10015",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "PayPal",
    emailVerified: false,
  },
];
const products: IProductInput[] = [
  // مد و پوشاک
  {
    name: "تی‌شرت نایک مردانه آستین بلند",
    slug: toSlug("Nike Mens Slim-fit Long-Sleeve T-Shirt"),
    category: "مد و پوشاک",
    images: ["/images/p11-1.jpg", "/images/p11-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 21.8,
    listPrice: 0,
    brand: "Nike",
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 11,
    description:
      "Made with chemicals safer for human health and the environment",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Green", "Red", "Black"],

    reviews: [],
  },
  {
    name: "تی‌شرت جرسیز آستین بلند ضخیم",
    slug: toSlug("Jerzees Long-Sleeve Heavyweight Blend T-Shirt"),
    category: "مد و پوشاک",
    images: [
      "/images/p12-1.jpg",
      "/images/p12-2.jpg",
      "/images/p12-3.jpg",
      "/images/p12-4.jpg",
    ],
    tags: ["featured"],
    isPublished: true,
    price: 23.78,
    listPrice: 0,
    brand: "Jerzees",
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description:
      "Made with sustainably sourced USA grown cotton; Shoulder-to-shoulder tape; double-needle coverstitched front neck; Set-in sleeves; Rib cuffs with concealed seams; Seamless body for a wide printing area",

    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Yellow", "Red", "Black"],

    reviews: [],
  },
  {
    name: "تی‌شرت مردانه جرسیز آستین بلند",
    slug: toSlug("Jerzees Men Long-Sleeve T-Shirt"),
    category: "مد و پوشاک",
    brand: "Jerzees",
    images: ["/images/p13-1.jpg", "/images/p13-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 13.86,
    listPrice: 16.03,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 13,
    description:
      "The Jerzees long sleeve t-shirt is made with dri-power technology that wicks away moisture to keep you cool and dry throughout your day. We also included a rib collar and cuffs for added durability, and a lay-flat collar for comfort. If you are looking for a versatile shirt that you can wear throughout the transitioning seasons, then look no further.",
    sizes: ["XL", "XXL"],
    colors: ["Green", "White"],

    reviews: [],
  },
  {
    name: "تی‌شرت مردانه دکروم ساده آستین بلند - راحت و نرم مدل یقه V",
    slug: toSlug(
      "Decrum Mens Plain Long Sleeve T-Shirt - Comfortable Soft Fashion V Neck Full Sleeves Jersey Shirts"
    ),
    category: "مد و پوشاک",
    brand: "Jerzees",
    images: ["/images/p14-1.jpg", "/images/p14-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 26.95,
    listPrice: 46.03,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 14,
    description:
      "Elevate your outfit with this soft long sleeve t shirt men. This full sleeves tee is the ultimate upgrade from your regular cotton t-shirt. ",
    sizes: ["XL", "XXL"],
    colors: ["Yellow", "White"],

    reviews: [],
  },
  {
    name: "تی‌شرت مردانه ماسل کماندر فیت تنگ - آستین کوتاه و بلند",
    slug: toSlug(
      "Muscle Cmdr Men's Slim Fit Henley Shirt Long&Short Business Sleeve Casual 3 Metal Buton Placket Casual Stylish T-Shirt"
    ),
    category: "مد و پوشاک",
    brand: " Muscle Cmdr",
    images: ["/images/p15-1.jpg", "/images/p15-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 29.99,
    listPrice: 35.99,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 54,
    countInStock: 15,
    description:
      "Slim Fit Design:Men's Muscle Slim Fit Button Henley Shirts are designed to fit snugly against your body, accentuating your muscles and creating a sleek silhouette that's perfect for any occasion. ",
    sizes: ["XL", "XXL"],
    colors: ["Green", "Yellow"],

    reviews: [],
  },
  {
    name: "تی‌شرت مردانه هینز آستین بلند ضخیم",
    slug: toSlug("Hanes Mens Long Sleeve Beefy Henley Shirt"),
    category: "مد و پوشاک",
    brand: "Jerzees",
    images: ["/images/p16-1.jpg", "/images/p16-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 25.3,
    listPrice: 32.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 16,
    numSales: 56,
    description:
      "Heavyweight cotton (Heathers are 60% cotton/40% polyester; Pebblestone is 75% cotton/25% polyester)",
    sizes: ["XL", "XXL"],
    colors: ["Grey", "White"],

    reviews: [],
  },
  // مد و پوشاک - شلوار جین
  {
    name: "شلوار جین مردانه سیلور جینز کو - مدل جیس فیت تنگ",
    slug: toSlug("Silver Jeans Co. Mens Jace Slim Fit Bootcut Jeans"),
    category: "مد و پوشاک",
    brand: "Silver Jeans Co",
    images: ["/images/p21-1.jpg", "/images/p21-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 54,
    numSales: 21,
    description:
      "Silver Jeans Co. Jace Slim Fit Bootcut Jeans - Consider Jace a modern cowboy jean. It sits below the waist and features a slim fit through the hip and thigh. Finished with an 18” bootcut leg opening that complements the slimmer silhouette while still fitting over boots",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],

    reviews: [],
  },
  {
    name: "شلوار جین مردانه لیوایز ۵۰۵ فیت معمولی",
    slug: toSlug(
      "Levi's mens 505 Regular Fit Jeans (Also Available in Big & Tall)"
    ),
    category: "مد و پوشاک",
    brand: "Levi's",
    images: ["/images/p22-1.jpg", "/images/p22-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 59.99,
    listPrice: 69.99,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 22,
    numSales: 54,
    description:
      "A veritable classic, this 505 is made to have a comfortable look and style.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],

    reviews: [],
  },
  {
    name: "شلوار جین مردانه اسنشالز فیت مستقیم کشی",
    slug: toSlug("Essentials Mens Straight-Fit Stretch Jean"),
    category: "مد و پوشاک",
    brand: "Essentials",
    images: ["/images/p23-1.jpg", "/images/p23-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 38.9,
    listPrice: 45,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 23,
    numSales: 54,
    description:
      "These classic 5-pocket straight-fit jeans are crafted with a bit of stretch for additional comfort and to help maintain their shape",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Grey", "Blue"],

    reviews: [],
  },
  {
    name: "شلوار جین مردانه بوفالو دیوید بیتون - مدل درایون ریلکس",
    slug: toSlug(
      "Buffalo David Bitton Mens Men's Driven Relaxed Denim JeansJeans"
    ),
    category: "مد و پوشاک",
    brand: "Buffalo David Bitton",
    images: ["/images/p24-1.jpg", "/images/p24-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 69.99,
    listPrice: 100,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 24,
    numSales: 53,
    description:
      "Stretch recycled denim jeans in an authentic and sanded wash blue. Features a comfortable low-rise waist with a relaxed fit at the leg. The distressed look gives these jeans an effortlessly worn-in feel. The eco-friendly logo patch in tan and red is at the back waistband. The signature maple leaf graphic is debossed at the zip-fly.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],

    reviews: [],
  },
  {
    name: "شلوار جین مردانه دیکیز فیت ریلکس نجاری",
    slug: toSlug("Dickies Mens Relaxed Fit Carpenter Jean"),
    category: "مد و پوشاک",
    brand: "Dickies",
    images: ["/images/p25-1.jpg", "/images/p25-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 25,
    numSales: 48,
    description:
      "Relaxed work jean with traditional carpenter-style pockets and logo patch at back pockets",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],

    reviews: [],
  },
  {
    name: "شلوار جین مردانه رنگلر پریمیوم - مدل کابوی کات فیت تنگ",
    slug: toSlug("Wrangler mens Premium Performance Cowboy Cut Slim Fit Jean"),
    category: "مد و پوشاک",
    brand: "Wrangler",
    images: ["/images/p26-1.jpg", "/images/p26-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 81.78,
    listPrice: 149.99,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 26,
    numSales: 48,
    description:
      "Designed with a functional fit in mind, these jeans are made to stack over your favorite pair of boots. Constructed with a slim fit in the waist, seat, and thigh, this jean is made for both function and comfort for long days in the saddle.",
    sizes: ["30Wx30L", "34Wx30L", "36Wx30L"],
    colors: ["Blue", "Grey"],

    reviews: [],
  },
  // موبایل و کامپیوتر - ساعت
  {
    name: "ساعت مردانه سیکو آنالوگ با صفحه سیاه",
    slug: toSlug("Seiko Men's Analogue Watch with Black Dial"),
    category: "موبایل و کامپیوتر",
    brand: "Seiko",
    images: ["/images/p31-1.jpg", "/images/p31-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 530.0,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 31,
    numSales: 48,
    description:
      "Casing: Case made of stainless steel Case shape: round Case colour: silver Glass: Hardlex Clasp type: Fold over clasp with safety",
    sizes: [],
    colors: [],

    reviews: [],
  },
  {
    name: "ساعت سیکو ۵ اسپورت SRPJ83 صفحه بژ نایلون اتوماتیک",
    slug: toSlug(
      "SEIKO 5 Sport SRPJ83 Beige Dial Nylon Automatic Watch, Beige, Automatic Watch"
    ),
    category: "موبایل و کامپیوتر",
    brand: "Seiko",
    images: ["/images/p32-1.jpg", "/images/p32-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 375.83,
    listPrice: 400,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 32,
    numSales: 48,
    description:
      "Seiko 5 Sports Collection Inspired by vintage field/aviator style: Automatic with manual winding capability",
    sizes: [],
    colors: [],

    reviews: [],
  },
  {
    name: "ساعت مردانه کاسیو آنالوگ کوارتز مقاوم - بند استیل نقره‌ای",
    slug: toSlug(
      "Casio Men's Heavy Duty Analog Quartz Stainless Steel Strap, Silver, 42 Casual Watch"
    ),
    category: "موبایل و کامپیوتر",
    brand: "Casio",
    images: ["/images/p33-1.jpg", "/images/p33-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 60.78,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 33,
    numSales: 48,
    description:
      "The Casio range is growing with this model  MWA-100H-1AVEF. Sporting a stainless steel case with a brushed finish, it will easily withstand all the shocks of everyday life.",
    sizes: [],
    colors: [],

    reviews: [],
  },
  {
    name: "ساعت کلاسیک کاسیو نقره‌ای استیل - نشانگر تاریخ",
    slug: toSlug(
      "Casio Classic Silver-Tone Stainless Steel Band Date Indicator Watch"
    ),
    category: "موبایل و کامپیوتر",
    brand: "Casio",
    images: ["/images/p34-1.jpg", "/images/p34-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 34.22,
    listPrice: 54.99,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 34,
    numSales: 48,
    description:
      "The new MTPVD01D-7EV is a classic 50 meter water resistant stainless steel watch now updated with a white dial. This elegant 3 hand, date display timepiece is perfect for any setting.",
    sizes: [],
    colors: [],

    reviews: [],
  },
  {
    name: "ساعت مردانه فسیل گرانت استیل کوارتز کرنوگراف",
    slug: toSlug("Fossil Men's Grant Stainless Steel Quartz Chronograph Watch"),
    category: "موبایل و کامپیوتر",
    brand: "Fossil",
    images: ["/images/p35-1.jpg", "/images/p35-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 171.22,
    listPrice: 225,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 35,
    numSales: 48,
    description:
      "Chronograph watch featuring silver- and blue-tone case, blue sunray dial, and silver-tone Roman numeral indices",
    sizes: [],
    colors: ["Blue", "Black", "Sliver"],

    reviews: [],
  },
  {
    name: "ساعت مردانه فسیل ماشین استیل کوارتز",
    slug: toSlug("Fossil Men's Machine Stainless Steel Quartz Watch"),
    category: "موبایل و کامپیوتر",
    brand: "Fossil",
    images: ["/images/p36-1.jpg", "/images/p36-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 158.21,
    listPrice: 229.0,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 36,
    numSales: 49,
    description:
      "In masculine black-on-black, our industrial-inspired Machine watch will add a fresh, modern touch to your casual look. This Machine watch also features a three hand movement on a stainless steel bracelet.",
    sizes: [],
    colors: ["Brown", "Sliver", "Black"],

    reviews: [],
  },
  // مد و پوشاک - کفش
  {
    name: "کفش ورزشی مردانه آدیداس گرند کورت ۲.۰",
    slug: toSlug("adidas Mens Grand Court 2.0 Training Shoes Training Shoes"),
    category: "مد و پوشاک",
    brand: "adidas",
    images: ["/images/p41-1.jpg", "/images/p41-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 81.99,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 41,
    numSales: 48,
    description:
      "Cloudfoam Comfort sockliner is ultra-soft and plush, with two layers of cushioning topped with soft, breathable mesh",
    sizes: ["8", "9", "10"],
    colors: ["White", "Black", "Grey"],

    reviews: [],
  },
  {
    name: "کفش مردانه زیتوپ پیاده‌روی و دویدن - کفش رسمی و ورزشی",
    slug: toSlug(
      "ziitop Men's Running Walking Shoes Fashion Sneakers Mesh Dress Shoes Business Oxfords Shoes Lightweight Casual Breathable Work Formal Shoes"
    ),
    category: "مد و پوشاک",
    brand: "ziitop",
    images: ["/images/p42-1.jpg", "/images/p42-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 39.97,
    listPrice: 49.96,
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 42,
    numSales: 50,
    description:
      "Cloudfoam Comfort sockliner is ultra-soft and plush, with two layers of cushioning topped with soft, breathable mesh",
    sizes: ["8", "9", "10"],
    colors: ["Beige", "Black", "Grey"],

    reviews: [],
  },
  {
    name: "کفش مردانه اسکچرز سامیتس - کفش کاری بدون بند",
    slug: toSlug(
      "Skechers mens Summits High Range Hands Free Slip-in Shoes Work shoe"
    ),
    category: "مد و پوشاک",
    brand: "Skechers",
    images: ["/images/p43-1.jpg", "/images/p43-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 99.99,
    listPrice: 0,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 43,
    numSales: 72,
    description:
      "Step into easy-wearing comfort with Skechers Hands Free Slip-ins™: Summits - High Range. Along with our Exclusive Heel Pillow™ holds your foot securely in place, this vegan style features a unique pop-up Skechers Slip-ins™ molded heel panel, a mesh upper with fixed laces",
    sizes: ["8", "9", "10"],
    colors: ["Navy", "Black", "Grey"],

    reviews: [],
  },
  {
    name: "کفش مردانه DLWKIPV دویدن و تنیس - کفش ورزشی ضد لغزش",
    slug: toSlug(
      "DLWKIPV Mens Running Shoes Tennis Cross Training Sneakers Fashion Non Slip Outdoor Walking Jogging Shoes Mesh Light Flexible Comfortable Breathable Shoes"
    ),
    category: "مد و پوشاک",
    brand: "DLWKIPV",
    images: ["/images/p44-1.jpg", "/images/p44-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 36.99,
    listPrice: 56.9,
    avgRating: 3.85,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 44,
    numSales: 72,
    description:
      "Design: Mesh vamp, ventilation. Sole anti-slip groove design, shock absorption and anti-slip. The inside of the shoe is wide and soft, bringing you a good comfortable experience",
    sizes: ["8", "9", "10", "11", "12"],
    colors: ["Brown", "Black", "Grey"],

    reviews: [],
  },
  {
    name: "کفش مردانه آسیکس GT-2000 13 دویدن",
    slug: toSlug("ASICS Men's GT-2000 13 Running Shoes"),
    category: "مد و پوشاک",
    brand: "ASICS",
    images: ["/images/p45-1.jpg", "/images/p45-2.jpg"],
    tags: ["new-arrival", "featured"],
    isPublished: true,
    price: 179.95,
    listPrice: 200,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 45,
    numSales: 64,
    description:
      "At least 50% of the shoe's main upper material is made with recycled content to reduce waste and carbon emissions",
    sizes: ["8", "9", "10", "11"],
    colors: ["Blue", "Black", "Grey"],

    reviews: [],
  },
  {
    name: "کفش مردانه وربریز شهری - فوق العاده راحت و رسمی",
    slug: toSlug(
      "Mens Wearbreeze Shoes, Urban - Ultra Comfortable Shoes, Breeze Shoes for Men, Men's Mesh Dress Sneakers Business Shoes"
    ),
    category: "مد و پوشاک",
    brand: "Generic",
    images: ["/images/p46-1.jpg", "/images/p46-2.jpg"],
    tags: ["best-seller", "todays-deal"],
    isPublished: true,
    price: 32.99,
    listPrice: 80,
    avgRating: 3.46,
    numReviews: 13,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    countInStock: 46,
    numSales: 48,
    description:
      "Cloudfoam Comfort sockliner is ultra-soft and plush, with two layers of cushioning topped with soft, breathable mesh",
    sizes: ["8", "9", "10", "11"],
    colors: ["Green", "Black", "Grey"],

    reviews: [],
  },

  // زنانه - پیراهن
  {
    name: "پیراهن مجلسی زنانه ساتن",
    slug: toSlug("Women Satin Evening Dress"),
    category: "مد و پوشاک - زنانه - پیراهن",
    images: ["/images/women-dress-1.jpg", "/images/women-dress-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 85.0,
    listPrice: 100.0,
    brand: "Fashion Style",
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 15,
    countInStock: 25,
    description:
      "پیراهن مجلسی شیک از جنس ساتن با کیفیت بالا، مناسب برای مهمانی‌ها و مراسم خاص",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "سرمه‌ای", "زرشکی"],
    reviews: [],
  },

  // زنانه - تاپ و بادی
  {
    name: "تاپ بافت زنانه آستین بلند",
    slug: toSlug("Women Long Sleeve Knit Top"),
    category: "مد و پوشاک - زنانه - تاپ و بادی",
    images: ["/images/women-top-1.jpg", "/images/women-top-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 35.0,
    listPrice: 45.0,
    brand: "Comfy Wear",
    avgRating: 4.3,
    numReviews: 8,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 4 },
      { rating: 5, count: 3 },
    ],
    numSales: 22,
    countInStock: 30,
    description: "تاپ بافت راحت و گرم، مناسب برای فصل پاییز و زمستان",
    sizes: ["S", "M", "L", "XL"],
    colors: ["کرم", "مشکی", "قهوه‌ای"],
    reviews: [],
  },

  // زنانه - شلوار جین
  {
    name: "شلوار جین زنانه اسکینی",
    slug: toSlug("Women Skinny Jeans"),
    category: "مد و پوشاک - زنانه - شلوار جین",
    images: ["/images/women-jeans-1.jpg", "/images/women-jeans-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 65.0,
    listPrice: 80.0,
    brand: "Denim Co",
    avgRating: 4.7,
    numReviews: 25,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 1 },
      { rating: 4, count: 5 },
      { rating: 5, count: 18 },
    ],
    numSales: 45,
    countInStock: 40,
    description: "شلوار جین اسکینی با فیت عالی و پارچه کشسان برای راحتی بیشتر",
    sizes: ["27", "28", "29", "30", "31", "32"],
    colors: ["آبی تیره", "مشکی", "آبی روشن"],
    reviews: [],
  },

  // زنانه - شومیز
  {
    name: "شومیز اداری زنانه کلاسیک",
    slug: toSlug("Women Classic Office Blouse"),
    category: "مد و پوشاک - زنانه - شومیز",
    images: ["/images/women-blouse-1.jpg", "/images/women-blouse-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 55.0,
    listPrice: 70.0,
    brand: "Office Style",
    avgRating: 4.4,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 6 },
      { rating: 5, count: 6 },
    ],
    numSales: 28,
    countInStock: 35,
    description: "شومیز شیک و کلاسیک مناسب برای محیط کار و مراسم رسمی",
    sizes: ["S", "M", "L", "XL"],
    colors: ["سفید", "آبی روشن", "صورتی"],
    reviews: [],
  },

  // زنانه - تی شرت
  {
    name: "تی شرت زنانه کتان نرم",
    slug: toSlug("Women Soft Cotton T-Shirt"),
    category: "مد و پوشاک - زنانه - تی شرت",
    images: ["/images/women-tshirt-1.jpg", "/images/women-tshirt-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 25.0,
    listPrice: 0,
    brand: "Cotton Comfort",
    avgRating: 4.6,
    numReviews: 32,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 8 },
      { rating: 5, count: 21 },
    ],
    numSales: 67,
    countInStock: 50,
    description: "تی شرت کتان نرم و تنفس پذیر، مناسب برای استفاده روزانه",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["سفید", "مشکی", "طوسی", "صورتی"],
    reviews: [],
  },

  // زنانه - شلوارک و اسکورت
  {
    name: "شلوارک تابستانی زنانه کتان",
    slug: toSlug("Women Summer Cotton Shorts"),
    category: "مد و پوشاک - زنانه - شلوارک و اسکورت",
    images: ["/images/women-shorts-1.jpg", "/images/women-shorts-2.jpg"],
    tags: ["todays-deal"],
    isPublished: true,
    price: 30.0,
    listPrice: 40.0,
    brand: "Summer Style",
    avgRating: 4.2,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 8 },
      { rating: 5, count: 7 },
    ],
    numSales: 35,
    countInStock: 45,
    description: "شلوارک کتان راحت و خنک برای روزهای گرم تابستان",
    sizes: ["S", "M", "L", "XL"],
    colors: ["بژ", "سفید", "آبی روشن"],
    reviews: [],
  },

  // زنانه - دامن
  {
    name: "دامن پلیسه زنانه میدی",
    slug: toSlug("Women Pleated Midi Skirt"),
    category: "مد و پوشاک - زنانه - دامن",
    images: ["/images/women-skirt-1.jpg", "/images/women-skirt-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 50.0,
    listPrice: 65.0,
    brand: "Elegant Wear",
    avgRating: 4.5,
    numReviews: 20,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 1 },
      { rating: 4, count: 8 },
      { rating: 5, count: 10 },
    ],
    numSales: 23,
    countInStock: 30,
    description:
      "دامن پلیسه شیک با طول میدی، مناسب برای استفاده در مناسبات مختلف",
    sizes: ["S", "M", "L", "XL"],
    colors: ["مشکی", "سرمه‌ای", "قهوه‌ای"],
    reviews: [],
  },

  // زنانه - ست
  {
    name: "ست دو تکه زنانه تونیک و شلوار",
    slug: toSlug("Women Two Piece Tunic Set"),
    category: "مد و پوشاک - زنانه - ست",
    images: ["/images/women-set-1.jpg", "/images/women-set-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 95.0,
    listPrice: 120.0,
    brand: "Coordinated Style",
    avgRating: 4.6,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 5 },
      { rating: 5, count: 8 },
    ],
    numSales: 19,
    countInStock: 25,
    description:
      "ست دو تکه شامل تونیک و شلوار هماهنگ، مناسب برای استفاده اداری و مهمانی",
    sizes: ["S", "M", "L", "XL"],
    colors: ["طوسی", "سرمه‌ای", "قهوه‌ای"],
    reviews: [],
  },

  // زنانه - ژاکت و پلیور
  {
    name: "ژاکت بافت زنانه ضخیم",
    slug: toSlug("Women Thick Knit Cardigan"),
    category: "مد و پوشاک - زنانه - ژاکت و پلیور",
    images: ["/images/women-cardigan-1.jpg", "/images/women-cardigan-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 75.0,
    listPrice: 90.0,
    brand: "Warm Wear",
    avgRating: 4.7,
    numReviews: 28,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 1 },
      { rating: 4, count: 6 },
      { rating: 5, count: 20 },
    ],
    numSales: 42,
    countInStock: 35,
    description: "ژاکت بافت گرم و نرم با کیفیت عالی برای فصل سرد",
    sizes: ["S", "M", "L", "XL"],
    colors: ["کرم", "طوسی", "مشکی"],
    reviews: [],
  },

  // زنانه - کفش
  {
    name: "کفش اسپرت زنانه راحتی",
    slug: toSlug("Women Comfortable Sports Shoes"),
    category: "مد و پوشاک - زنانه - کفش",
    images: ["/images/women-shoes-1.jpg", "/images/women-shoes-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 120.0,
    listPrice: 150.0,
    brand: "Comfort Walk",
    avgRating: 4.8,
    numReviews: 35,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 1 },
      { rating: 4, count: 5 },
      { rating: 5, count: 28 },
    ],
    numSales: 58,
    countInStock: 40,
    description: "کفش اسپرت بسیار راحت با طراحی مدرن و کیفیت بالا",
    sizes: ["36", "37", "38", "39", "40", "41"],
    colors: ["سفید", "مشکی", "طوسی"],
    reviews: [],
  },

  // زنانه - کیف
  {
    name: "کیف دستی زنانه چرم طبیعی",
    slug: toSlug("Women Natural Leather Handbag"),
    category: "مد و پوشاک - زنانه - کیف",
    images: ["/images/women-bag-1.jpg", "/images/women-bag-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 180.0,
    listPrice: 220.0,
    brand: "Leather Craft",
    avgRating: 4.9,
    numReviews: 22,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 20 },
    ],
    numSales: 31,
    countInStock: 25,
    description: "کیف دستی شیک از چرم طبیعی با فضای مناسب و طراحی زیبا",
    sizes: ["یک سایز"],
    colors: ["مشکی", "قهوه‌ای", "کرم"],
    reviews: [],
  },

  // مردانه - شلوارک
  {
    name: "شلوارک ورزشی مردانه نایک",
    slug: toSlug("Men Nike Sports Shorts"),
    category: "مد و پوشاک - مردانه - شلوارک",
    images: ["/images/men-shorts-1.jpg", "/images/men-shorts-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 45.0,
    listPrice: 55.0,
    brand: "Nike",
    avgRating: 4.6,
    numReviews: 42,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 12 },
      { rating: 5, count: 26 },
    ],
    numSales: 78,
    countInStock: 60,
    description: "شلوارک ورزشی راحت و قابل تنفس برای ورزش و فعالیت‌های روزانه",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["مشکی", "طوسی", "آبی"],
    reviews: [],
  },

  // مردانه - شلوار
  {
    name: "شلوار کتان مردانه کلاسیک",
    slug: toSlug("Men Classic Cotton Pants"),
    category: "مد و پوشاک - مردانه - شلوار",
    images: ["/images/men-pants-1.jpg", "/images/men-pants-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 70.0,
    listPrice: 85.0,
    brand: "Classic Style",
    avgRating: 4.4,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 8 },
      { rating: 5, count: 7 },
    ],
    numSales: 24,
    countInStock: 35,
    description: "شلوار کتان کلاسیک با فیت مناسب برای استفاده اداری و روزانه",
    sizes: ["30", "32", "34", "36", "38", "40"],
    colors: ["مشکی", "سرمه‌ای", "خاکستری"],
    reviews: [],
  },

  // مردانه - پیراهن
  {
    name: "پیراهن مردانه آستین بلند اداری",
    slug: toSlug("Men Long Sleeve Office Shirt"),
    category: "مد و پوشاک - مردانه - پیراهن",
    images: ["/images/men-shirt-1.jpg", "/images/men-shirt-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 60.0,
    listPrice: 75.0,
    brand: "Office Pro",
    avgRating: 4.5,
    numReviews: 25,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 8 },
      { rating: 5, count: 14 },
    ],
    numSales: 38,
    countInStock: 45,
    description: "پیراهن اداری با کیفیت بالا و پارچه نرم مناسب برای محیط کار",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["سفید", "آبی روشن", "صورتی"],
    reviews: [],
  },

  // مردانه - پولوشرت
  {
    name: "پولوشرت مردانه کتان درجه یک",
    slug: toSlug("Men Premium Cotton Polo Shirt"),
    category: "مد و پوشاک - مردانه - پولوشرت",
    images: ["/images/men-polo-1.jpg", "/images/men-polo-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 50.0,
    listPrice: 65.0,
    brand: "Polo Style",
    avgRating: 4.7,
    numReviews: 31,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 1 },
      { rating: 4, count: 6 },
      { rating: 5, count: 23 },
    ],
    numSales: 52,
    countInStock: 40,
    description: "پولوشرت کتان درجه یک با طراحی کلاسیک و راحت",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["سفید", "آبی", "مشکی", "قرمز"],
    reviews: [],
  },

  // مردانه - جین
  {
    name: "شلوار جین مردانه راسته",
    slug: toSlug("Men Straight Fit Jeans"),
    category: "مد و پوشاک - مردانه - جین",
    images: ["/images/men-jeans-1.jpg", "/images/men-jeans-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 80.0,
    listPrice: 100.0,
    brand: "Denim Pro",
    avgRating: 4.6,
    numReviews: 48,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 15 },
      { rating: 5, count: 28 },
    ],
    numSales: 89,
    countInStock: 55,
    description: "شلوار جین راسته با کیفیت عالی و دوام بالا",
    sizes: ["30", "32", "34", "36", "38", "40"],
    colors: ["آبی تیره", "مشکی", "آبی روشن"],
    reviews: [],
  },

  // مردانه - هودی و سویشرت
  {
    name: "هودی مردانه گرم زمستانی",
    slug: toSlug("Men Warm Winter Hoodie"),
    category: "مد و پوشاک - مردانه - هودی و سویشرت",
    images: ["/images/men-hoodie-1.jpg", "/images/men-hoodie-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 65.0,
    listPrice: 80.0,
    brand: "Winter Wear",
    avgRating: 4.5,
    numReviews: 22,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 8 },
      { rating: 5, count: 11 },
    ],
    numSales: 34,
    countInStock: 30,
    description: "هودی گرم و راحت با جیب کانگورو برای فصل سرد",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["مشکی", "طوسی", "سرمه‌ای"],
    reviews: [],
  },

  // مردانه - کفش
  {
    name: "کفش اسپرت مردانه رانینگ",
    slug: toSlug("Men Running Sport Shoes"),
    category: "مد و پوشاک - مردانه - کفش",
    images: [
      "/images/men-running-shoes-1.jpg",
      "/images/men-running-shoes-2.jpg",
    ],
    tags: ["featured"],
    isPublished: true,
    price: 140.0,
    listPrice: 170.0,
    brand: "Run Fast",
    avgRating: 4.8,
    numReviews: 56,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 8 },
      { rating: 5, count: 44 },
    ],
    numSales: 102,
    countInStock: 65,
    description: "کفش اسپرت حرفه‌ای برای دویدن و ورزش با تکنولوژی کشش ضربه",
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["مشکی", "سفید", "آبی"],
    reviews: [],
  },

  // بچه گانه - دختر 1.5 تا 6 سال
  {
    name: "پیراهن دخترانه طرح پروانه",
    slug: toSlug("Girls Butterfly Print Dress"),
    category: "مد و پوشاک - بچه گانه - دختر 1.5 تا 6 سال",
    images: ["/images/girls-dress-1.jpg", "/images/girls-dress-2.jpg"],
    tags: ["new-arrival"],
    isPublished: true,
    price: 35.0,
    listPrice: 45.0,
    brand: "Kids Fashion",
    avgRating: 4.6,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 5 },
      { rating: 5, count: 9 },
    ],
    numSales: 28,
    countInStock: 35,
    description: "پیراهن زیبا و راحت برای دختربچه‌ها با طرح پروانه رنگارنگ",
    sizes: ["2-3 سال", "3-4 سال", "4-5 سال", "5-6 سال"],
    colors: ["صورتی", "آبی", "زرد"],
    reviews: [],
  },

  // بچه گانه - دختر 6 تا 14 سال
  {
    name: "ست دختر نوجوان شلوار و تونیک",
    slug: toSlug("Teen Girls Tunic Pants Set"),
    category: "مد و پوشاک - بچه گانه - دختر 6 تا 14 سال",
    images: ["/images/teen-girls-set-1.jpg", "/images/teen-girls-set-2.jpg"],
    tags: ["featured"],
    isPublished: true,
    price: 55.0,
    listPrice: 70.0,
    brand: "Teen Style",
    avgRating: 4.4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 1 },
      { rating: 4, count: 4 },
      { rating: 5, count: 6 },
    ],
    numSales: 18,
    countInStock: 25,
    description: "ست زیبا و مدرن برای دختران نوجوان شامل تونیک و شلوار",
    sizes: ["6-7 سال", "8-9 سال", "10-11 سال", "12-14 سال"],
    colors: ["سرمه‌ای", "صورتی", "طوسی"],
    reviews: [],
  },

  // بچه گانه - نوزاد 0 تا 18 ماه
  {
    name: "ست نوزادی نخی 3 تکه",
    slug: toSlug("Baby Cotton 3 Piece Set"),
    category: "مد و پوشاک - بچه گانه - نوزاد 0 تا 18 ماه",
    images: ["/images/baby-set-1.jpg", "/images/baby-set-2.jpg"],
    tags: ["best-seller"],
    isPublished: true,
    price: 40.0,
    listPrice: 50.0,
    brand: "Baby Comfort",
    avgRating: 4.8,
    numReviews: 25,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 4 },
      { rating: 5, count: 20 },
    ],
    numSales: 62,
    countInStock: 40,
    description: "ست نوزادی نرم و راحت از جنس نخ خالص شامل بادی، شلوار و کلاه",
    sizes: ["0-3 ماه", "3-6 ماه", "6-12 ماه", "12-18 ماه"],
    colors: ["آبی", "صورتی", "زرد", "سفید"],
    reviews: [],
  },
];

const reviews = [
  {
    rating: 1,
    title: "Poor quality",
    comment:
      "Very disappointed. The item broke after just a few uses. Not worth the money.",
  },
  {
    rating: 2,
    title: "Disappointed",
    comment:
      "Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
  },
  {
    rating: 2,
    title: "Needs improvement",
    comment:
      "It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
  },
  {
    rating: 3,
    title: "not bad",
    comment:
      "This product is decent, the quality is good but it could use some improvements in the details.",
  },
  {
    rating: 3,
    title: "Okay, not great",
    comment:
      "It works, but not as well as I hoped. Quality is average and lacks some finishing.",
  },
  {
    rating: 3,
    title: "Good product",
    comment:
      "This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.",
  },
  {
    rating: 4,
    title: "Pretty good",
    comment:
      "Solid product! Great value for the price, but there's room for minor improvements.",
  },
  {
    rating: 4,
    title: "Very satisfied",
    comment:
      "Good product! High quality and worth the price. Would consider buying again.",
  },
  {
    rating: 4,
    title: "Absolutely love it!",
    comment:
      "Perfect in every way! The quality, design, and comfort exceeded all my expectations.",
  },
  {
    rating: 4,
    title: "Exceeded expectations!",
    comment:
      "Fantastic product! High quality, feels durable, and performs well. Highly recommend!",
  },
  {
    rating: 5,
    title: "Perfect purchase!",
    comment:
      "Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
  },
  {
    rating: 5,
    title: "Highly recommend",
    comment:
      "Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
  },
  {
    rating: 5,
    title: "Just what I needed",
    comment:
      "Exactly as described! Quality exceeded my expectations, and it arrived quickly.",
  },
  {
    rating: 5,
    title: "Excellent choice!",
    comment:
      "This product is outstanding! Everything about it feels top-notch, from material to functionality.",
  },
  {
    rating: 5,
    title: "Couldn't ask for more!",
    comment:
      "Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
  },
];

const data: Data = {
  users,
  reviews,
  products,
  headerMenus: [
    {
      name: "مد و پوشاک",
      href: "/search?category=مد و پوشاک",
    },
    {
      name: "آرایش و زیبایی",
      href: "/search?category=آرایش و زیبایی",
    },
    {
      name: "موبایل و کامپیوتر",
      href: "/search?category=موبایل و کامپیوتر",
    },
    {
      name: "اسباب بازی و گجت",
      href: "/search?category=اسباب بازی و گجت",
    },
    {
      name: "حیوانات خانگی",
      href: "/search?category=حیوانات خانگی",
    },
    {
      name: "ویتامین و دارو",
      href: "/search?category=ویتامین و دارو",
    },
  ],
  carousels: [
    {
      title: "محبوب‌ترین کفش‌ها برای فروش",
      buttonCaption: "خرید کنید",
      image: "/images/banner3.jpg",
      url: "/search?category=مد و پوشاک",
      isPublished: true,
    },
    {
      title: "پرفروش‌ترین تی‌شرت‌ها",
      buttonCaption: "خرید کنید",
      image: "/images/banner1.jpg",
      url: "/search?category=مد و پوشاک",
      isPublished: true,
    },
    {
      title: "بهترین تخفیف‌ها روی ساعت‌های مچی",
      buttonCaption: "بیشتر ببینید",
      image: "/images/banner2.jpg",
      url: "/search?category=موبایل و کامپیوتر",
      isPublished: true,
    },
  ],
};

export default data;
